# RT-Thread building script for component

from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd]

CPPDEFINES = [
    'HAVE_CCONFIG_H',
    'closesocket=close'
]
group = DefineGroup('webserver', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)
group = group + LinkBridge()

Return('group')
