from building import *

cwd        = GetCurrentDir()
src        = []
CCFLAGS    = ' -nostdinc'
CPPPATH    = [cwd + '/include']
CPPDEFINES = ['__STDC_ISO_10646__=201206L', '_STDC_PREDEF_H']
LIBS       = ['crt', 'c', 'm', 'gcc']
LIBPATH    = [cwd + '/lib']

if GetDepend('RT_USING_GCC_MUSL'):
    LIBS   = ['c', 'gcc']
    group  = DefineGroup('sdk', src, depend = [''], LIBS = LIBS)
else:
    group = DefineGroup('sdk', src, depend = [''], CCFLAGS = CCFLAGS, CPPPATH = CPPPATH, 
        CPPDEFINES = CPPDEFINES, LIBPATH = LIBPATH, LIBS = LIBS)

Return('group')

