# RT-Thread building script for component

from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd]

CPPDEFINES = [
        'RT_USING_NEWLIB',
        'HAVE_CCONFIG_H',
]
group = DefineGroup('vi', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

list = os.listdir(cwd)
for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        group = group + SConscript(os.path.join(d, 'SConscript'))



Return('group')
