# RT-Thread building script for component

from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd]

CPPDEFINES = [
        'RT_USING_NEWLIB',
        'HAVE_CCONFIG_H',
        'closesocket=close'
]
group = DefineGroup('wget', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)
group = group + LinkBridge()

Return('group')

